/**
 * @readonly
 * @description Unicorn preset rules for ESLint
 *
 * @since 1.0.0
 */
const UNICORN_RULES: Record<string, unknown> = {
  "@unicorn/consistent-empty-array-spread": "error",
  "@unicorn/consistent-existence-index-check": "error",
  "@unicorn/consistent-function-scoping": "error",
  "@unicorn/custom-error-definition": "error",
  "@unicorn/empty-brace-spaces": "error",
  "@unicorn/error-message": "error",
  "@unicorn/filename-case": [ "error", {
    "case": "kebabCase"
  } ],
  "@unicorn/no-array-push-push": "error",
  "@unicorn/no-document-cookie": "error",
  "@unicorn/no-empty-file": "error",
  "@unicorn/no-instanceof-array": "error",
  "@unicorn/no-invalid-fetch-options": "error",
  "@unicorn/no-lonely-if": "error",
  "@unicorn/no-negated-condition": "error",
  "@unicorn/no-nested-ternary": "error",
  "@unicorn/no-new-array": "error",
  "@unicorn/no-new-buffer": "error",
  "@unicorn/no-object-as-default-parameter": "error",
  "@unicorn/no-process-exit": "error",
  "@unicorn/no-single-promise-in-promise-methods": "error",
  "@unicorn/no-static-only-class": "error",
  "@unicorn/no-thenable": "error",
  "@unicorn/no-typeof-undefined": "error",
  "@unicorn/no-unnecessary-await": "error",
  "@unicorn/no-unused-properties": "error",
  "@unicorn/no-useless-fallback-in-spread": "error",
  "@unicorn/no-useless-length-check": "error",
  "@unicorn/no-useless-promise-resolve-reject": "error",
  "@unicorn/no-useless-spread": "error",
  "@unicorn/no-useless-switch-case": "error",
  "@unicorn/no-useless-undefined": "error",
  "@unicorn/no-zero-fractions": "error",
  "@unicorn/number-literal-case": "error",
  "@unicorn/numeric-separators-style": "error",
  "@unicorn/prefer-array-flat": "error",
  "@unicorn/prefer-array-flat-map": "error",
  "@unicorn/prefer-array-index-of": "error",
  "@unicorn/prefer-array-some": "error",
  "@unicorn/prefer-at": "error",
  "@unicorn/prefer-blob-reading-methods": "error",
  "@unicorn/prefer-code-point": "error",
  "@unicorn/prefer-date-now": "error",
  "@unicorn/prefer-default-parameters": "error",
  "@unicorn/prefer-dom-node-append": "error",
  "@unicorn/prefer-dom-node-dataset": "error",
  "@unicorn/prefer-dom-node-remove": "error",
  "@unicorn/prefer-dom-node-text-content": "error",
  "@unicorn/prefer-event-target": "error",
  "@unicorn/prefer-export-from": "error",
  "@unicorn/prefer-includes": "error",
  "@unicorn/prefer-json-parse-buffer": "error",
  "@unicorn/prefer-keyboard-event-key": "error",
  "@unicorn/prefer-logical-operator-over-ternary": "error",
  "@unicorn/prefer-math-min-max": "error",
  "@unicorn/prefer-modern-dom-apis": "error",
  "@unicorn/prefer-modern-math-apis": "error",
  "@unicorn/prefer-native-coercion-functions": "error",
  "@unicorn/prefer-negative-index": "error",
  "@unicorn/prefer-node-protocol": "error",
  "@unicorn/prefer-number-properties": "error",
  "@unicorn/prefer-object-from-entries": "error",
  "@unicorn/prefer-optional-catch-binding": "error",
  "@unicorn/prefer-prototype-methods": "error",
  "@unicorn/prefer-query-selector": "error",
  "@unicorn/prefer-regexp-test": "error",
  "@unicorn/prefer-set-has": "error",
  "@unicorn/prefer-set-size": "error",
  "@unicorn/prefer-spread": "error",
  "@unicorn/prefer-string-replace-all": "error",
  "@unicorn/prefer-string-slice": "error",
  "@unicorn/prefer-string-starts-ends-with": "error",
  "@unicorn/prefer-string-trim-start-end": "error",
  "@unicorn/prefer-structured-clone": "error",
  "@unicorn/prefer-switch": "error",
  "@unicorn/prefer-ternary": "error",
  "@unicorn/prefer-top-level-await": "error",
  "@unicorn/prefer-type-error": "error",
  "@unicorn/relative-url-style": "error",
  "@unicorn/switch-case-braces": [ "error", "always" ],
  "@unicorn/throw-new-error": "error"
};

export {
  UNICORN_RULES
};
