name: Deploy
on:
  push:
    branches:
      - "main"
  workflow_dispatch:
permissions:
  id-token: write
  contents: write
  pull-requests: write

jobs:
  call-npm-package-deploy:
    uses: OGS-GmbH/reusable-github-actions/.github/workflows/npm-package-bump.yml@main
    secrets:
      GH_DEPLOY_TOKEN: ${{ secrets.GH_DEPLOY_TOKEN }}
      NPM_ORG_OGS_GMBH_CI: ${{ secrets.NPM_ORG_OGS_GMBH_CI }}
